# Use an official Java runtime parent image
FROM tomcat:10.0

# Copy the WAR file into the webapps directory of the Tomcat container
COPY ../../target/TodoList-1.0.war /usr/local/tomcat/webapps/ROOT.war