version: '3'
services:
  web:
    build: .
    environment:
      - DATABASE_URL=jdbc:mysql://db:3306/
      - DATABASE_USER=my_user
      - DATABASE_PASSWORD=my_password
    ports:
      - "8080:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '1'    # Limit to 1 CPU
          memory: 1G    # Limit to 1GB memory

  db:
    image: "mysql:8.0"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my_root_password
      MYSQL_DATABASE: todolist
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
volumes:
  db-data:

